2021-01-20 13:03:00,848 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 14:25:07,903 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 14:41:02,422 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 14:41:08,106 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 14:54:55,129 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 15:07:17,245 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 15:07:52,716 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 15:08:12,270 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 15:22:45,736 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-21 15:26:39,778 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-22 15:04:22,926 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:42]
2021-01-22 15:15:58,227 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:44]
2021-01-22 15:37:13,454 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:38:16,903 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:39:15,215 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:39:16,578 ERROR: Exception on / [GET] [in /home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/selmanbaskaya/Desktop/microblog/app/routes.py", line 38, in index
    return render_template('index.html', title='Home', form=form,
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% for message in messages %}
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% for message in messages %}
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% for message in messages %}
  [Previous line repeated 964 more times]
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 10, in top-level template code
    {% extends "base.html" %}
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/utils.py", line 381, in get
    return self[key]
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/utils.py", line 426, in __getitem__
    self._remove(key)
RecursionError: maximum recursion depth exceeded in comparison
2021-01-22 15:39:23,446 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:39:25,818 ERROR: Exception on / [GET] [in /home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/selmanbaskaya/Desktop/microblog/app/routes.py", line 38, in index
    return render_template('index.html', title='Home', form=form,
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% for message in messages %}
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% for message in messages %}
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 35, in top-level template code
    {% for message in messages %}
  [Previous line repeated 964 more times]
  File "/home/selmanbaskaya/Desktop/microblog/app/templates/base.html", line 10, in top-level template code
    {% extends "base.html" %}
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/utils.py", line 381, in get
    return self[key]
  File "/home/selmanbaskaya/Desktop/microblog/venv/lib/python3.8/site-packages/jinja2/utils.py", line 426, in __getitem__
    self._remove(key)
RecursionError: maximum recursion depth exceeded in comparison
2021-01-22 15:40:22,812 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:40:41,082 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:42:45,540 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:43:58,964 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:45:08,442 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:46:19,550 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:47:56,597 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:48:16,003 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:48:45,915 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:49:27,403 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
2021-01-22 15:51:29,619 INFO: Microblog startup [in /home/selmanbaskaya/Desktop/microblog/app/__init__.py:46]
